### ISSUE TITLE
Music Volume is not saving

### ISSUE THREAD

**Issue by leavmealonepy** [shivasiddharth/GassistPi#381]
Command ,,Hey Google, set music volume to maximum"
works only once, after reboot or changing source of stream from for example. from google music to youtube or after requesting new youtube song, music volume is muted and I need to say command again.

EDIT: I see that music volume is going to maximum as I have requested before after requesting different random Google Assistant command. For example: Set reminder or Hey Google <beep> Nothing.
--so
It looks like music is muted after request utill you ask Google Assistant for something (random). 
You need to do that everytime when you request any song.

**Comment by shivasiddharth** [comment]
Can you add this line `self.check_delete("/home/pi/.mediavolume.json")` under` def stop_vlc(self):` in the mediaplayer.py file and then try.

**Comment by leavmealonepy** [comment]
like
```
    def stop_vlc(self):
	self.check_delete("/home/pi/.mediavolume.json")
        print('stopping vlc')
        self.libvlc_player.stop()
```
?

**Comment by leavmealonepy** [comment]
Assistant wont boot after this change @UP

**Comment by shivasiddharth** [comment]
If it was entered correctly, there should not be any issues. Manually start the assistant and post the error.

**Comment by leavmealonepy** [comment]
Ok, I have fixed it, it was Python Syntax error with tabing and spacing.
Now after manual start it shows:
```
/home/pi/env/bin/python -u /home/pi/GassistPi/src/main.py --device_model_id 'pi-home-a4520-google-pi-home-lq8tmd'
[028f3058] pulse audio output error: PulseAudio server connection failure: Connection refused
[0292e8f0] pulse audio output error: PulseAudio server connection failure: Connection refused
device_model_id: pi-home-a4520-google-pi-home-lq8tmd
device_id: 9086AE97C3552300715A398856BC3792

ON_MUTED_CHANGED:
  {"is_muted": false}
ON_START_FINISHED
```
I haven't tested that its fixed yet, but isn't PulseAudio a reason of problems??

**Comment by shivasiddharth** [comment]
No. This is usual, nothing to worry.

**Comment by leavmealonepy** [comment]
Google music volume was set to maximum after reboot but youtube was still muted.
After I have changed back from youtube to google music, it was muted too.

And I dont know why, maybe its my accent fault, but usually Hey Google Pause Music worked, now it won't propably after this change.

**Comment by leavmealonepy** [comment]
```
ON_CONVERSATION_TURN_STARTED
ON_END_OF_UTTERANCE
ON_RECOGNIZING_SPEECH_FINISHED:
  {"text": "stop music"}
sh: 1: /home/pi/.mediavolume.json: Permission denied
stopping vlc
ON_RENDER_RESPONSE:
  {"text": "Nothing's playing at the moment.", "type": 0}
ON_RESPONDING_STARTED:
  {"is_error_response": false}
ON_RESPONDING_FINISHED
ON_CONVERSATION_TURN_FINISHED:
  {"with_follow_on_turn": false}
```
Okay, now I see its Permission denied, the fun  fact is that I am running it on root access account :V

**Comment by leavmealonepy** [comment]
started with sudo:
```
ON_CONVERSATION_TURN_STARTED
ON_END_OF_UTTERANCE
ON_RECOGNIZING_SPEECH_FINISHED:
  {"text": "stream Arctic Monkeys balaclava"}
sh: 1: /home/pi/.mediavolume.json: Permission denied
stopping vlc
Getting youtube link
High Performance MPEG 1.0/2.0/2.5 Audio Player for Layers 1, 2 and 3
	version 1.23.8; written and copyright by Michael Hipp and others
	free software (LGPL) without any warranty but with best wishes
```

and Google Music:

```
Artist not found
Artist not found
Artist not found
Artist not found
sh: 1: /home/pi/.player.json: Permission denied
sh: 1: /home/pi/.trackqueue.json: Permission denied
[014d8410] pulse audio output error: PulseAudio server connection failure: Connection refused
ON_CONVERSATION_TURN_FINISHED:
  {"with_follow_on_turn": false}
```
Still Permission denied lol

**Comment by leavmealonepy** [comment]
No permission denied now, but music volume is still not saving

**Comment by shivasiddharth** [comment]
I have added a bug tag, will try and fix it in the next couple of days

**Comment by shivasiddharth** [comment]
I have fixed the issue, you need not modify much, just check the commit and add those few lines to your existing script.

**Comment by leavmealonepy** [comment]
Pulled from github and reedited my login details, I can confirm - fix is working.
Good job like always! Thanks!

btw. Your response time is brilliant

**Comment by Akshaykkapoor** [comment]
ON_CONVERSATION_TURN_STARTED
ON_END_OF_UTTERANCE
ON_RECOGNIZING_SPEECH_FINISHED:
  {"text": "play all songs from Google Music"}
stopping vlc
ON_CONVERSATION_TURN_FINISHED:
  {"with_follow_on_turn": false}

 
still getting the stopping vlc as response , pulled the code from git today ..
